### ISSUE TITLE
Transfer this repo to a personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/realtime#7]
@jonocarroll et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by jonocarroll** [comment]
I'm happy to have this transferred to my personal account, where I will make it public. All authors are welcome to fork the project and develop independently. I do not know if I will ever continue development myself (I would like to).

**Comment by maelle** [comment]
Transfer requested! :heavy_check_mark:

**Comment by jonocarroll** [comment]
Done. Thank you!
